### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghost** [mfitzp/kropbot#1]
I want to be able to use and modify kropbot, however I can not do that legally without a license.
Could you please add a license to the repo, for example MIT License?
Thank you.

**Comment by mfitzp** [comment]
Hey thanks for the reminder, an MIT license file has now been added.

Just out curiosity, what are your plans for using the code?

**Comment by ghost** [comment]
I am planning on making it work with a L298N controller (not the best controller but it works).
Also I will remove the video streaming and use jsmpeg instead, it is great to stream video at a very low latency.
